version: '3'

services:
    # mysql:
    #     image: "mysql:5.7"
    #     restart: always
    #     hostname: mysql
    #     container_name: mysql
    #     environment:
    #       - MYSQL_PASSWORD=mysql
    #       - MYSQL_USER=root
    #       - MYSQL_ROOT_PASSWORD=mysql
    #       - MYSQL_DATABASE=budgets
    #       - MYSQL_PORT=3306
    #       - REACT_APP_SERVER_PORT=3000
    #     healthcheck:
    #         test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
    #         timeout: 20s
    #         retries: 10 
    #     cap_add:
    #         - SYS_NICE
    #     command: --default-authentication-plugin=mysql_native_password
    #     ports:
    #         - "3306:3306"
    #     networks: 
    #         - backend 
    web:
        build: ./backend
        # depends_on: 
        #     - mysql
        expose:
            - "3000"
        ports:
             - "3000:3000"
        # entrypoint: ["/bin/bash", "./entrypoint.sh"]
        # environment:
        #   - MYSQL_USER=root
        #   - MYSQL_PASSWORD=mysql
        #   - MYSQL_ROOT_PASSWORD=mysql
        #   - MYSQL_DATABASE=budgets
        #   - REACT_APP_SERVER_PORT=3000
        #   - MYSQL_PORT=3306
        #   - MYSQL_HOST=mysql
        # links:
        #     - mysql
        command: npm run start
        # networks: 
        #     - backend  
    # client:
    #     stdin_open: true
    #     build: ./frontend
    #     environment:
    #         - MYSQL_PASSWORD=mysql
    #         - MYSQL_DATABASE=budgets
    #         - REACT_APP_SERVER_PORT=3000
    #         - NODE_PATH=src
    #     expose:
    #         - "5000"
    #     ports:
    #         - "5000:5000"
    #     volumes:
    #         - ./frontend/src:/app/src
    #     links:
    #         - web
    #     command: yarn start
    #     networks: 
    #         - backend 

# networks: 
#     backend:       
    
        
    
